#!/bin/sh

ZIP=$1
TEMPDIR=$2
ROOTDIR=$3

echo Creating $@...
mkdir "$TEMPDIR"
cd "$TEMPDIR"

mkdir include
cp -r "$ROOTDIR"/third_party/range-v3/include/range include/
cp -r "$ROOTDIR"/third_party/range-v3/include/meta include/
cp "$ROOTDIR"/third_party/debug_assert/debug_assert.hpp include/
rsync -r --include '*.hpp' --include '*/' --exclude '*' "$ROOTDIR"/jules include/

echo -e "=== jules ===\n\n" > LICENSE
cat "$ROOTDIR"/license.txt >> LICENSE

echo -e "\n\n=== debug_assert ===\n\n" >> LICENSE
cat "$ROOTDIR"/third_party/debug_assert/LICENSE >> LICENSE

echo -e "\n\n=== range-v3 ===\n\n" >> LICENSE
cat "$ROOTDIR"/third_party/range-v3/LICENSE.txt >> LICENSE

zip -r "$ZIP" include LICENSE

cd "$ROOTDIR"
mv "$TEMPDIR"/"$ZIP" .
rm -rf "$TEMPDIR"
